"""empty message

Revision ID: 57a87587a90f
Revises: 
Create Date: 2025-02-26 15:52:16.797306

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '57a87587a90f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('electricians',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=False),
    sa.Column('years_experience', sa.Integer(), nullable=True),
    sa.Column('hourly_rate', sa.Integer(), nullable=True),
    sa.Column('available_from', sa.DateTime(), nullable=True),
    sa.Column('preferred_locations', sa.String(), nullable=True),
    sa.Column('primary_license_state', sa.Enum('NSW', 'VIC', 'QLD', 'WA', 'SA', 'TAS', 'NT', 'ACT', name='australianstate'), nullable=False),
    sa.Column('insurance_status', sa.Boolean(), nullable=True),
    sa.Column('insurance_expiry', sa.DateTime(), nullable=True),
    sa.Column('insurance_policy_number', sa.String(), nullable=True),
    sa.Column('verified_status', sa.Boolean(), nullable=True),
    sa.Column('profile_completion', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('equipment_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['equipment_categories.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('HIRER', 'OPERATOR', 'ADMIN', name='userrole'), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('certifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('electrician_id', sa.Integer(), nullable=True),
    sa.Column('certification_type', sa.Enum('WORKING_AT_HEIGHTS', 'CONFINED_SPACE', 'EWP', 'WHITE_CARD', 'HV_SWITCHING', 'HAZARDOUS_AREA', 'TEST_AND_TAG', 'SOLAR_GRID_CONNECT', 'BATTERY_STORAGE', 'UNDERGROUND_CABLES', 'MINE_SITE_INDUCTION', 'SURFACE_MINING', 'UNDERGROUND_MINING', 'GAS_TESTING', 'EXPLOSION_PROTECTION', 'FIRST_AID', 'CPR', 'ASBESTOS_AWARENESS', 'LOTO', name='certificationtype'), nullable=True),
    sa.Column('issuing_body', sa.String(), nullable=False),
    sa.Column('issue_date', sa.DateTime(), nullable=False),
    sa.Column('expiry_date', sa.DateTime(), nullable=True),
    sa.Column('certificate_number', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['electrician_id'], ['electricians.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('licenses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('electrician_id', sa.Integer(), nullable=True),
    sa.Column('license_type', sa.Enum('ELECTRICAL_CONTRACTOR', 'QUALIFIED_SUPERVISOR', 'ELECTRICAL_WORKER', name='licensetype'), nullable=True),
    sa.Column('license_number', sa.String(), nullable=False),
    sa.Column('issuing_state', sa.Enum('NSW', 'VIC', 'QLD', 'WA', 'SA', 'TAS', 'NT', 'ACT', name='australianstate'), nullable=True),
    sa.Column('issue_date', sa.DateTime(), nullable=False),
    sa.Column('expiry_date', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('restrictions', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['electrician_id'], ['electricians.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('license_number')
    )
    op.create_table('operators',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('business_name', sa.String(length=255), nullable=False),
    sa.Column('abn', sa.String(length=11), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('service_radius', sa.Integer(), nullable=False),
    sa.Column('operating_hours', sa.String(), nullable=True),
    sa.Column('website', sa.String(length=255), nullable=True),
    sa.Column('address_line1', sa.String(length=255), nullable=False),
    sa.Column('address_line2', sa.String(length=255), nullable=True),
    sa.Column('suburb', sa.String(length=100), nullable=False),
    sa.Column('state', sa.String(length=50), nullable=False),
    sa.Column('postcode', sa.String(length=10), nullable=False),
    sa.Column('moderation_status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', name='moderationstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('business_name')
    )
    op.create_table('projects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('electrician_id', sa.Integer(), nullable=True),
    sa.Column('project_type', sa.Enum('MINING', 'RENEWABLE', 'COMMERCIAL', 'INDUSTRIAL', 'RESIDENTIAL', name='projecttype'), nullable=True),
    sa.Column('project_value', sa.Integer(), nullable=True),
    sa.Column('start_date', sa.DateTime(), nullable=True),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('tools_used', sa.String(), nullable=True),
    sa.Column('role_description', sa.String(), nullable=True),
    sa.Column('voltage_levels', sa.String(), nullable=True),
    sa.Column('role', sa.Enum('LEAD', 'SUPERVISOR', 'TECHNICIAN', 'APPRENTICE', name='projectrole'), nullable=True),
    sa.Column('specialties', sa.String(), nullable=True),
    sa.Column('team_size', sa.Integer(), nullable=True),
    sa.Column('safety_incidents', sa.Integer(), nullable=True),
    sa.Column('compliance_standards', sa.String(), nullable=True),
    sa.Column('key_achievements', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['electrician_id'], ['electricians.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('qualifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('electrician_id', sa.Integer(), nullable=True),
    sa.Column('qualification_type', sa.Enum('CERT_III_ELECTROTECHNOLOGY', 'CERT_IV_INDUSTRIAL_ELECTRONICS', 'DIPLOMA_ELECTRICAL', 'ADVANCED_DIPLOMA_ELECTRICAL', name='qualificationtype'), nullable=True),
    sa.Column('institution', sa.String(), nullable=False),
    sa.Column('completion_date', sa.DateTime(), nullable=False),
    sa.Column('certificate_number', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['electrician_id'], ['electricians.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('skills',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('electrician_id', sa.Integer(), nullable=True),
    sa.Column('specialty', sa.Enum('INDUSTRIAL_AUTOMATION', 'POWER_DISTRIBUTION', 'RENEWABLE_ENERGY', 'MINING_OPERATIONS', 'COMMERCIAL_INSTALLATION', 'MAINTENANCE', name='specialtyarea'), nullable=True),
    sa.Column('years_experience', sa.Integer(), nullable=True),
    sa.Column('proficiency_level', sa.Integer(), nullable=True),
    sa.Column('last_used_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['electrician_id'], ['electricians.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('equipment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('operator_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('specifications', sa.String(), nullable=True),
    sa.Column('daily_rate', sa.Float(), nullable=True),
    sa.Column('weekly_rate', sa.Float(), nullable=True),
    sa.Column('monthly_rate', sa.Float(), nullable=True),
    sa.Column('availability_status', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['equipment_categories.id'], ),
    sa.ForeignKeyConstraint(['operator_id'], ['operators.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('equipment')
    op.drop_table('skills')
    op.drop_table('qualifications')
    op.drop_table('projects')
    op.drop_table('operators')
    op.drop_table('licenses')
    op.drop_table('certifications')
    op.drop_table('users')
    op.drop_table('equipment_categories')
    op.drop_table('electricians')
    # ### end Alembic commands ###
